creation_timestamp: 1763046695974
current_stage: Production
deployment_job_state: null
description: null
last_updated_timestamp: 1763047253573
model_id: m-656c6bab24f347e7b72bae8aaefea696
name: SalaryPredictionModel
run_id: 4004a9f673984549bed430714f7818a0
run_link: null
source: models:/m-656c6bab24f347e7b72bae8aaefea696
status: READY
status_message: null
storage_location: file:///home/akram/mlops_salary_capstone/mlruns/983816932083839018/models/m-656c6bab24f347e7b72bae8aaefea696/artifacts
user_id: null
version: 3
